AWSTemplateFormatVersion: "2010-09-09"
Resources:
#--------------------Create a lambda IAM role
  lambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow # Allow the lambda service to assume the role
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies: # Attach policies to the role that provides full s3 permissions for the lambda role
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

#--------------------Create a lambda function
  lambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Role: !GetAtt lambdaRole.Arn
      Runtime: nodejs20.x
      Handler: lambda.lambda_handler
      Code:
        S3Bucket: testmyseanvbu
        S3Key: function.zip
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", "lambda-function"]]
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue 'AllowAllSecurityGroup'
        SubnetIds: 
          - !ImportValue 'PublicSubnet2'